## influxdb image version
## ref: https://hub.docker.com/r/library/influxdb/tags/
##
image:
  repository: "kapacitor"
  tag: "1.5.3-alpine"
  pullPolicy: "IfNotPresent"

## Specify a service type, defaults to NodePort
## ref: http://kubernetes.io/docs/user-guide/services/
##
service:
  type: ClusterIP

## Persist data to a persitent volume
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  accessMode: ReadWriteOnce
  size: 8Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 2Gi
    cpu: 2
    
## Set the URL of InfluxDB instance to create subscription on
## ref: https://docs.influxdata.com/kapacitor/v1.1/introduction/getting_started/
##
config:
  # global_tags:
  #   cluster: "mycluster"
  data_dir: /var/lib/kapacitor
  http:
    bind_address: ":9092"
    https_enabled: true
    https_certificate: /var/run/certs/tls.crt
    https_private_key: /var/run/certs/tls.key
  influxdb:
    enabled: true
    default: true
    username: splice_admin
    password: Passw0rd!
    name: kapacitor
    urls: https://data-influxdb.tick:8086
    ssl_cert: /var/run/certs/tls.crt
    ssl_key: /var/run/certs/tls.key
    insecure_skip_verify: true
    subscription_protocol: https
