## Image Settings
##
image:
  repository: "quay.io/influxdb/chronograf"
  tag: "latest"
  pullPolicy: "Always"

## Specify a service type
## ClusterIP is default
## ref: http://kubernetes.io/docs/user-guide/services/
##
service:
  replicas: 1
  type: ClusterIP

## Persist data to a persitent volume
##
persistence:
  enabled: true
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  accessMode: ReadWriteOnce
  size: 8Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 2Gi
    cpu: 2
    
## Configure the ingress object to hook into existing infastructure
## ref : http://kubernetes.io/docs/user-guide/ingress/
## OPTIONALLY you can set .Values.ingress.secretName to set which secret to use    
## 
ingress:
  enabled: true
  tls: true
  hostname: chronograf.splicemachine-dev.io
  annotations:
    kubernetes.io/ingress.class: "nginx"
    secretName: splicemachine-dev-io-cert
    kubernetes.io/tls-acme: "false"

## OAuth Settings for OAuth Providers
## More information -> https://github.com/influxdata/chronograf/blob/master/docs/auth.md
##
oauth:
  # Need to set to true to use any of the oauth options
  enabled: true
  # Used for JWT to support running multiple copies of Chronograf
  token_secret: $pl1c3M4ch1n3
  github:
    enabled: false
    client_id: CHANGE_ME
    client_secret: CHANGE_ME
    # This is a comma seperated list of GH organizations (OPTIONAL)
    gh_orgs: ""
  google:
    enabled: false
    client_id: CHANGE_ME
    client_secret: CHANGE_ME
    public_url: "" # eg. http://chronograf.foobar.com
    # This is a comma seperated list of Google Apps domains (OPTIONAL)
    google_domains: ""
  heroku:
    enabled: false
    client_id: CHANGE_ME
    client_secret: CHANGE_ME
    # This is a comma seperated list of Heroku organizations (OPTIONAL)
    he_orgs: ""
  auth0:
    enabled: true
    domain: https://splicemachine-dev.auth0.com
    client_id: zdS4y0EQmNSioimlHgM2D4HOMpcc2VcE
    client_secret: nNRmUjqRRzqnaxLLbL16SMUx2iS45altxmQudBAbCPICL51weY7rf0qSAoqeyBJu
    public_url: https://chronograf.splicemachine-dev.io
